language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - pip install -r requirements.txt
script:
  - python -m unittest -v tests.test_parsers
after_success:
  - codecov
