language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install pytest-cov
  - pip install codecov
install:
  - pip install -r requirements.txt
script:
  - py.test --cov-report=xml --cov=myproj tests/
after_success:
  - codecov
